spring:
  application:
    name: spring-boot-service

  jackson:
    serialization:
      write_dates_as_timestamps: false         # Date serialization configuration

server:
  ssl:
    enabled: false
  port: 8080