spring:
  application:
    name: spring-boot-service
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        all-namespaces: true # Servlet container configuration
      reload:
        period: 1000
        enabled: true
        mode: event
      config:
        enabled: true
        name: "spring-boot-service"
        sources:
          - name: "spring-boot-service"
        fail-fast: true

server:
  ssl:
    enabled: false
  port: 8080