apiVersion: v1
kind: Service
metadata:
{{- with .Values.application.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    service: {{ template "application.fullname" . }}
  name: {{ template "application.fullname" . }}
spec:
  ports:
  - name: {{ .Values.application.service.name }}
    port: {{ .Values.application.service.port }}
    targetPort: {{ .Values.application.service.targetPort }}
  selector:
    service: {{ template "application.fullname" . }}
