# Service account for the Elasticsearch service (for ACL enforcement)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName}}
  namespace: {{ template "application.namespace" . }}
